/**
 * Only selector for the adapt implementation.
 * Today: in-browser fixture. Later: switch to ./http without changing callers.
 * Fixture track owns fixture.ts content; do not edit this file from that track.
 */
export { adapt } from "./fixture";
export type { AdaptFn } from "./port";
